### ISSUE TITLE
-215:Assertion failed (EDSR x2)

### ISSUE THREAD

**Issue by erxson** [mgagvani/minecraft_texture_upscaler#2]
errors like

Error OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\core\src\merge.dispatch.cpp:129: error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'cv::merge'
 with ./temp/assets/minecraft\textures\environment\rain.png. Skipping.
Error OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\core\src\merge.dispatch.cpp:129: error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'cv::merge'
 with ./temp/assets/minecraft\textures\environment\snow.png. Skipping.
Spent 0.6809980869293213 seconds upscaling 3ch ./temp/assets/minecraft\textures\environment\sun.png
Error OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\core\src\merge.dispatch.cpp:129: error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'cv::merge'
 with ./temp/assets/minecraft\textures\font\accented.png. Skipping.
Spent 44.89030861854553 seconds upscaling 4ch ./temp/assets/minecraft\textures\font\ascii.png
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Error OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\core\src\merge.dispatch.cpp:129: error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'cv::merge'
 with ./temp/assets/minecraft\textures\gui\container\villager2.png. Skipping.
 Error OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\core\src\merge.dispatch.cpp:129: error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'cv::merge'
 with ./temp/assets/minecraft\textures\gui\container\brewing_guide_left.png. Skipping.
Error OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\core\src\merge.dispatch.cpp:129: error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'cv::merge'
 with ./temp/assets/minecraft\textures\gui\container\brewing_guide_right.png. Skipping.
 Error OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\core\src\merge.dispatch.cpp:129: error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'cv::merge'
 with ./temp/assets/minecraft\textures\font\nonlatin_european.png. Skipping.
Error OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\core\src\merge.dispatch.cpp:129: error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'cv::merge'
 with ./temp/assets/minecraft\textures\gui\accessibility.png. Skipping.

**Comment by mgagvani** [comment]
@erxson 

Few questions to try and debug:

1. What OS are you using? System specs?
2. What texture pack are you trying to upscale(so I can try to replicate issue).
3. Did the other images successfully upscale?

**Comment by erxson** [comment]
1. Windows 10 Home. i5-7300hq (2.5 GHz) 16 GB RAM, 1050 ti mobile
2. Vanilla Tweaks
3. Yes

**Comment by mgagvani** [comment]
Ok, so these images in particular (rain.png, snow.png, accented.png ...) seem to have some weird attributes (their color calibration is non-standard) which `libpng` doesn't seem to like. Try opening each of the files in a photo editor and re-saving them, and then re-run the script. @erxson

If that doesn't work, I'll try to re-produce the issue on my machine and upload a fix.
